<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.Vulkan" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" />
    <PackageReference Include="Silk.NET.Windowing" />

    <PackageReference Include="SharpGLTF.Core" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Istok.Core\Istok.Core.csproj" />
    <ProjectReference Include="..\..\src\Istok.Rendering\Istok.Rendering.csproj"/>
    <ProjectReference Include="..\..\src\Istok\Istok.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Assets\**\*.*">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
