<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>com.companyname.AndroidExamplesRunner</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Silk.NET.Input.Sdl" />
    <PackageReference Include="Silk.NET.SDL" />
    <PackageReference Include="Silk.NET.Vulkan" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" />
    <PackageReference Include="Silk.NET.Windowing.Sdl" />
    <PackageReference Include="Ultz.Native.SDL" />
    
    <PackageReference Include="Microsoft.Maui.Essentials" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Istok.Rendering\Istok.Rendering.csproj"/>
    <ProjectReference Include="..\..\src\Istok\Istok.csproj"/>
    <ProjectReference Include="..\Examples\Examples.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <AndroidAsset Include="..\Assets\**\*.*">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AndroidAsset>
  </ItemGroup>
</Project>
