<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Silk.NET.Vulkan" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.MVK" />
    <PackageReference Include="Silk.NET.Windowing.Common" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Silk.NET.Vulkan.Extensions\Silk.NET.Vulkan.Extensions.csproj" />
  </ItemGroup>

</Project>
